tasks:
  - name: Start Zitadel
    init: |
      docker compose pull
      export ZITADEL_EXTERNALDOMAIN=$(gp url 8080)
      export ZITADEL_EXTERNALPORT=8080
      export ZITADEL_EXTERNALSECURE=true
    command: |
      docker compose -p zitadel up

ports:
  - name: Zitadel
    description: Zitadel admin console + API
    port: 8080
    visibility: public
