tasks:
  - name: Start Zitadel
    init: |
      docker compose pull
    command: |
      ZITADEL_EXTERNALDOMAIN=zitadel.$(gp url 8080) ZITADEL_EXTERNALSECURE=true ZITADEL_EXTERNALPORT=443 docker compose -p zitadel up

ports:
  - name: Zitadel
    description: Zitadel admin console + API
    port: 443
    visibility: public
