tasks:
  - name: Start Zitadel
    init: |
      docker compose pull
    command: |
      docker-compose run \
        -e ZITADEL_EXTERNALDOMAIN=$(gp url 8080) \
        -e ZITADEL_EXTERNALSECURE=true \
        zitadel

ports:
  - name: Zitadel
    description: Zitadel admin console + API
    port: 8080
    visibility: public
