tasks:
  - name: Start Zitadel
    init: |
      docker compose pull
    command: |
      ZITADEL_EXTERNALDOMAIN=$(gp url 8080 | sed 's|http[s]*://||') ZITADEL_EXTERNALSECURE=true docker-compose -p zitadel up

ports:
  - name: Zitadel
    description: Zitadel admin console + API
    port: 8080
    visibility: public
