tasks:
  - name: Start Zitadel
    init: |
      docker compose pull
    command: |
      docker-compose -p zitadel up

ports:
  - name: Zitadel
    description: Zitadel admin console + API
    port: 8080
    visibility: public
